### ISSUE TITLE
Problem with "source_root" parameter

### ISSUE THREAD

**Issue by harnash** [Cimpress-MCP/git2consul#33]
It seems that adding `source_root` parameter causes folders to be truncated by one char.

Setup:
1. I have set `poz-dev/` as `source_root` in my git2consul config
2. In my repo I have path: `poz-dev/service/settings`

Problems
1. After running git2consul I get `ervice/settings` in Consul's KV
2. Entry which holds info about the revision instead of `master.ref` is named just `f`

**Comment by ryanbreen** [comment]
Yikes. I'll take a look.

**Comment by ryanbreen** [comment]
I think v0.10.3 should fix this.

**Comment by harnash** [comment]
Thanks. It seems to work but I still get weird revision entry name: `ef` (the key which holds the last revision).

`{"name":"git2consul","hostname":"wolfpit","pid":47392,"level":10,"msg":"Adding key config/ef, value:\n6bbe10acf47ae39c78ee1699e5a3de3da4e08b74","time":"2015-11-04T10:38:27.041Z","v":0}`

**Comment by ryanbreen** [comment]
Can you post your git2consul config.json?

**Comment by ryanbreen** [comment]
Never mind.  Pretty sure I got it.

**Comment by harnash** [comment]
Yup. You got that right!
