### ISSUE TITLE
Strange problem: sync stalled

### ISSUE THREAD

**Issue by harnash** [Cimpress-MCP/git2consul#47]
I have a test repo to illustrate the problem [here](https://github.com/harnash/git2consul_test.git). You can see the individual commits.

My config looks like this:
```javascript
{
  "version": "1.0",
  "repos": [
    {
      "name": "config",
      "url": "https://github.com/harnash/git2consul_test.git",
      "source_root": "config/",
      "branches": [
        "master"
      ],
      "include_branch_name" : false,
      "hooks": [
        {
          "type": "polling",
          "interval": "1"
        }
      ]
    },
    {
      "name": "registry",
      "url": "https://github.com/harnash/git2consul_test.git",
      "source_root": "registry/",
      "branches": [
        "master"
      ],
      "include_branch_name" : false,
      "hooks": [
        {
          "type": "polling",
          "interval": "1"
        }
      ]
    }
  ],
  "logger": {
    "name": "git2consul",
    "streams": [
      {
        "level": "debug",
        "stream": "process.stdout"
      }
    ]
  }
}
```

So after a while the synchronisation stopped for no good reason. I've noticed this on my dev instances too. After a while it just stops and even restarting doesn't help, only removing whole folder on Consul KV forces it to restore whole tree. I'm suspecting that it might be due that my two repos in git2consul points to the same repo and branch on Github.

Here is the dump from my logs:
```javascript
{"name":"git2consul","hostname":"1e8ebe2b6d54","pid":1,"level":30,"msg":"git2consul is running","time":"2016-02-05T12:23:22.488Z","v":0}
{"name":"git2consul","hostname":"1e8ebe2b6d54","pid":1,"level":30,"msg":"Initting repo config","time":"2016-02-05T12:23:22.492Z","v":0}
{"name":"git2consul","hostname":"1e8ebe2b6d54","pid":1,"level":30,"msg":"Initting branch /tmp/config /tmp/config/master","time":"2016-02-05T12:23:22.493Z","v":0}
{"name":"git2consul","hostname":"1e8ebe2b6d54","pid":1,"level":30,"msg":"Initting repo registry","time":"2016-02-05T12:23:22.494Z","v":0}
{"name":"git2consul","hostname":"1e8ebe2b6d54","pid":1,"level":30,"msg":"Initting branch /tmp/registry /tmp/registry/master","time":"2016-02-05T12:23:22.494Z","v":0}
{"name":"git2consul","hostname":"1e8ebe2b6d54","pid":1,"level":40,"msg":"Purging branch cache /tmp/config/master for branch master in repo config","time":"2016-02-05T12:23:22.495Z","v":0}
{"name":"git2consul","hostname":"1e8ebe2b6d54","pid":1,"level":40,"msg":"Purging branch cache /tmp/registry/master for branch master in repo registry","time":"2016-02-05T12:23:22.496Z","v":0}
{"name":"git2consul","hostname":"1e8ebe2b6d54","pid":1,"level":30,"msg":"Initialized branch master from registry","time":"2016-02-05T12:23:23.354Z","v":0}
{"name":"git2consul","hostname":"1e8ebe2b6d54","pid":1,"level":20,"msg":"Branches initialized","time":"2016-02-05T12:23:23.355Z","v":0}
{"name":"git2consul","hostname":"1e8ebe2b6d54","pid":1,"level":20,"msg":"Polling hook initialized with 1 minute intervals","time":"2016-02-05T12:23:23.358Z","v":0}
{"name":"git2consul","hostname":"1e8ebe2b6d54","pid":1,"level":30,"msg":"Loaded repo registry","time":"2016-02-05T12:23:23.359Z","v":0}
{"name":"git2consul","hostname":"1e8ebe2b6d54","pid":1,"level":30,"msg":"Initialized branch master from config","time":"2016-02-05T12:23:23.368Z","v":0}
{"name":"git2consul","hostname":"1e8ebe2b6d54","pid":1,"level":20,"msg":"Branches initialized","time":"2016-02-05T12:23:23.369Z","v":0}
{"name":"git2consul","hostname":"1e8ebe2b6d54","pid":1,"level":20,"msg":"Polling hook initialized with 1 minute intervals","time":"2016-02-05T12:23:23.370Z","v":0}
{"name":"git2consul","hostname":"1e8ebe2b6d54","pid":1,"level":30,"msg":"Loaded repo config","time":"2016-02-05T12:23:23.370Z","v":0}
{"name":"git2consul","hostname":"1e8ebe2b6d54","pid":1,"level":20,"msg":"Updates in branch master complete","time":"2016-02-05T12:24:53.256Z","v":0}
{"name":"git2consul","hostname":"1e8ebe2b6d54","pid":1,"level":20,"msg":"Updates in branch master complete","time":"2016-02-05T12:25:53.118Z","v":0}
{"name":"git2consul","hostname":"1e8ebe2b6d54","pid":1,"level":20,"msg":"Updates in branch master complete","time":"2016-02-05T12:26:53.126Z","v":0}
```
After that it just stays like that. After restart it does pick up the new files but it does not remove the old one (which were deleted on repo).

Log after restart:
```javascript
{"name":"git2consul","hostname":"fe8de965417b","pid":1,"level":30,"msg":"git2consul is running","time":"2016-02-05T12:47:06.516Z","v":0}
{"name":"git2consul","hostname":"fe8de965417b","pid":1,"level":30,"msg":"Initting repo config","time":"2016-02-05T12:47:06.520Z","v":0}
{"name":"git2consul","hostname":"fe8de965417b","pid":1,"level":30,"msg":"Initting branch /tmp/config /tmp/config/master","time":"2016-02-05T12:47:06.521Z","v":0}
{"name":"git2consul","hostname":"fe8de965417b","pid":1,"level":30,"msg":"Initting repo registry","time":"2016-02-05T12:47:06.522Z","v":0}
{"name":"git2consul","hostname":"fe8de965417b","pid":1,"level":30,"msg":"Initting branch /tmp/registry /tmp/registry/master","time":"2016-02-05T12:47:06.522Z","v":0}
{"name":"git2consul","hostname":"fe8de965417b","pid":1,"level":40,"msg":"Purging branch cache /tmp/config/master for branch master in repo config","time":"2016-02-05T12:47:06.524Z","v":0}
{"name":"git2consul","hostname":"fe8de965417b","pid":1,"level":40,"msg":"Purging branch cache /tmp/registry/master for branch master in repo registry","time":"2016-02-05T12:47:06.525Z","v":0}
{"name":"git2consul","hostname":"fe8de965417b","pid":1,"level":30,"msg":"Initialized branch master from registry","time":"2016-02-05T12:47:08.526Z","v":0}
{"name":"git2consul","hostname":"fe8de965417b","pid":1,"level":20,"msg":"Branches initialized","time":"2016-02-05T12:47:08.527Z","v":0}
{"name":"git2consul","hostname":"fe8de965417b","pid":1,"level":20,"msg":"Polling hook initialized with 1 minute intervals","time":"2016-02-05T12:47:08.528Z","v":0}
{"name":"git2consul","hostname":"fe8de965417b","pid":1,"level":30,"msg":"Loaded repo registry","time":"2016-02-05T12:47:08.529Z","v":0}
{"name":"git2consul","hostname":"fe8de965417b","pid":1,"level":30,"msg":"Initialized branch master from config","time":"2016-02-05T12:47:08.535Z","v":0}
{"name":"git2consul","hostname":"fe8de965417b","pid":1,"level":20,"msg":"Branches initialized","time":"2016-02-05T12:47:08.536Z","v":0}
{"name":"git2consul","hostname":"fe8de965417b","pid":1,"level":20,"msg":"Polling hook initialized with 1 minute intervals","time":"2016-02-05T12:47:08.537Z","v":0}
{"name":"git2consul","hostname":"fe8de965417b","pid":1,"level":30,"msg":"Loaded repo config","time":"2016-02-05T12:47:08.538Z","v":0}
```

**Comment by ryanbreen** [comment]
Interesting!  Thanks for this bug report.  We need to do a better job of monitoring the polling activity to make sure this doesn't happen: there must be some case where an exception or missed callback breaks the loop.

I'll give that some thought, thanks!

**Comment by harnash** [comment]
It might be the `git mv` operation that moves all the contents of one folder to the other that causing the problems. I've noticed it hangs after the same operation on another repo.

**Comment by harnash** [comment]
I just wanted to ask if there is any progress on that ticket?

**Comment by ryanbreen** [comment]
Unfortunately, not yet, sorry.

**Comment by ryanbreen** [comment]
I haven't figured out what's going on here, but I think I've ruled out it being due to two repo configs pointing to the same branch: I did some work to validate that we are isolated both on the local filesystem and in the Consul KV in the case of `source_root`, and that all looks good.

Next step is to do some testing with mv operations.

**Comment by harnash** [comment]
Here are the steps I can reproduce the problem everytime:

First checkout the master branch of https://github.com/harnash/git2consul_test.git
Checkout to revision 76a921700352e38e5174231de68b0d3af6359b69 and create separate branch (in my example it is called `reproduce`

Configure git2consul with settings:
```
{
  "version": "1.0",
  "repos": [
    {
      "name": "config",
      "url": "https://github.com/harnash/git2consul_test.git",
      "source_root": "config/",
      "branches": [
        "reproduce"
      ],
      "include_branch_name" : false,
      "hooks": [
        {
          "type": "polling",
          "interval": "1"
        }
      ]
    },
    {
      "name": "registry",
      "url": "https://github.com/harnash/git2consul_test.git",
      "source_root": "registry/",
      "branches": [
        "reproduce"
      ],
      "include_branch_name" : false,
      "hooks": [
        {
          "type": "polling",
          "interval": "1"
        }
      ]
    }
  ],
  "logger": {
    "name": "git2consul",
    "streams": [
      {
        "level": "trace",
        "stream": "process.stdout"
      }
    ]
  }
}
```

Run git2consul and you should get output:

```
{"name":"git2consul","hostname":"ff8e8bc03f90","pid":1,"level":30,"msg":"git2consul is running","time":"2016-02-26T13:23:15.864Z","v":0}
{"name":"git2consul","hostname":"ff8e8bc03f90","pid":1,"level":30,"msg":"Initting repo config","time":"2016-02-26T13:23:15.871Z","v":0}
{"name":"git2consul","hostname":"ff8e8bc03f90","pid":1,"level":30,"msg":"Initting branch /tmp/config /tmp/config/reproduce","time":"2016-02-26T13:23:15.872Z","v":0}
{"name":"git2consul","hostname":"ff8e8bc03f90","pid":1,"level":30,"msg":"Initting repo registry","time":"2016-02-26T13:23:15.872Z","v":0}
{"name":"git2consul","hostname":"ff8e8bc03f90","pid":1,"level":30,"msg":"Initting branch /tmp/registry /tmp/registry/reproduce","time":"2016-02-26T13:23:15.873Z","v":0}
{"name":"git2consul","hostname":"ff8e8bc03f90","pid":1,"level":40,"msg":"Purging branch cache /tmp/config/reproduce for branch reproduce in repo config","time":"2016-02-26T13:23:15.874Z","v":0}
{"name":"git2consul","hostname":"ff8e8bc03f90","pid":1,"level":40,"msg":"Purging branch cache /tmp/registry/reproduce for branch reproduce in repo registry","time":"2016-02-26T13:23:15.875Z","v":0}
{"name":"git2consul","hostname":"ff8e8bc03f90","pid":1,"level":30,"msg":"Initialized branch reproduce from registry","time":"2016-02-26T13:23:17.065Z","v":0}
{"name":"git2consul","hostname":"ff8e8bc03f90","pid":1,"level":20,"msg":"Branches initialized","time":"2016-02-26T13:23:17.066Z","v":0}
{"name":"git2consul","hostname":"ff8e8bc03f90","pid":1,"level":20,"msg":"Polling hook initialized with 1 minute intervals","time":"2016-02-26T13:23:17.067Z","v":0}
{"name":"git2consul","hostname":"ff8e8bc03f90","pid":1,"level":30,"msg":"Loaded repo registry","time":"2016-02-26T13:23:17.067Z","v":0}
{"name":"git2consul","hostname":"ff8e8bc03f90","pid":1,"level":30,"msg":"Initialized branch reproduce from config","time":"2016-02-26T13:23:17.072Z","v":0}
{"name":"git2consul","hostname":"ff8e8bc03f90","pid":1,"level":20,"msg":"Branches initialized","time":"2016-02-26T13:23:17.072Z","v":0}
{"name":"git2consul","hostname":"ff8e8bc03f90","pid":1,"level":20,"msg":"Polling hook initialized with 1 minute intervals","time":"2016-02-26T13:23:17.073Z","v":0}
{"name":"git2consul","hostname":"ff8e8bc03f90","pid":1,"level":30,"msg":"Loaded repo config","time":"2016-02-26T13:23:17.073Z","v":0}
```

Now do: 
```
git cherry-pick 1c69aa3e9081cf7653570b453d3fb95c27c804c1
git push
```

and git2consul should pickup the changes"
```
{"name":"git2consul","hostname":"ff8e8bc03f90","pid":1,"level":20,"msg":"Updates in branch reproduce complete","time":"2016-02-26T13:24:43.805Z","v":0}
{"name":"git2consul","hostname":"ff8e8bc03f90","pid":1,"level":20,"msg":"Updates in branch reproduce complete","time":"2016-02-26T13:25:43.733Z","v":0}
```

Then again:
```
git cherry-pick 0783dce7eb627f003668788b0807cf3fc3db909a
git push
```

And git2consul is no longer syncing....

Here is output with `trace` enabled:

```
$ node node_modules/git2consul --endpoint 192.168.99.100
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":30,"msg":"git2consul is running","time":"2016-02-26T15:11:35.071Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":30,"msg":"Initting repo config","time":"2016-02-26T15:11:35.075Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":30,"msg":"Initting branch /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/config /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/config/reproduce","time":"2016-02-26T15:11:35.076Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":30,"msg":"Initting repo registry","time":"2016-02-26T15:11:35.076Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":30,"msg":"Initting branch /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/registry /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/registry/reproduce","time":"2016-02-26T15:11:35.076Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Running git log -n 1 --pretty=format:\"%H\" in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/config/reproduce","time":"2016-02-26T15:11:35.077Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Running git log -n 1 --pretty=format:\"%H\" in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/registry/reproduce","time":"2016-02-26T15:11:35.081Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stdout:\ne4db78cdc0f4eccb54fae099cfaedfe0b54502d1","time":"2016-02-26T15:11:35.103Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Running git pull origin reproduce in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/registry/reproduce","time":"2016-02-26T15:11:35.104Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stdout:\nefd6d007cb0d898915480a5f07393709da1a0fa9","time":"2016-02-26T15:11:35.106Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Running git pull origin reproduce in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/config/reproduce","time":"2016-02-26T15:11:35.106Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stdout:\nAlready up-to-date.","time":"2016-02-26T15:11:35.927Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stderr:\nFrom https://github.com/harnash/git2consul_test\n * branch            reproduce  -> FETCH_HEAD\n + efd6d00...76a9217 reproduce  -> origin/reproduce  (forced update)","time":"2016-02-26T15:11:35.927Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Running git log -n 1 --pretty=format:\"%H\" in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/config/reproduce","time":"2016-02-26T15:11:35.928Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stdout:\nAlready up-to-date.","time":"2016-02-26T15:11:35.929Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stderr:\nFrom https://github.com/harnash/git2consul_test\n * branch            reproduce  -> FETCH_HEAD\n + e4db78c...76a9217 reproduce  -> origin/reproduce  (forced update)","time":"2016-02-26T15:11:35.929Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Running git log -n 1 --pretty=format:\"%H\" in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/registry/reproduce","time":"2016-02-26T15:11:35.929Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stdout:\nefd6d007cb0d898915480a5f07393709da1a0fa9","time":"2016-02-26T15:11:35.935Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stdout:\ne4db78cdc0f4eccb54fae099cfaedfe0b54502d1","time":"2016-02-26T15:11:35.939Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Running git ls-tree --name-status -r HEAD in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/config/reproduce","time":"2016-02-26T15:11:35.941Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Running git ls-tree --name-status -r HEAD in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/registry/reproduce","time":"2016-02-26T15:11:35.944Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stdout:\nconfig/A/foo\nconfig/B/bar\nregistry/X/test\nregistry/Y/key1","time":"2016-02-26T15:11:35.952Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Handling record config/A/foo of type M","time":"2016-02-26T15:11:35.953Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Attempting to read \"/var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/config/reproduce/config/A/foo\"","time":"2016-02-26T15:11:35.953Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Handling record config/B/bar of type M","time":"2016-02-26T15:11:35.954Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Attempting to read \"/var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/config/reproduce/config/B/bar\"","time":"2016-02-26T15:11:35.954Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Handling record registry/X/test of type M","time":"2016-02-26T15:11:35.954Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Handling record registry/Y/key1 of type M","time":"2016-02-26T15:11:35.954Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stdout:\nconfig/A/foo\nconfig/B/bar\nregistry/X/test","time":"2016-02-26T15:11:35.956Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Handling record config/A/foo of type M","time":"2016-02-26T15:11:35.956Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Handling record config/B/bar of type M","time":"2016-02-26T15:11:35.956Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Handling record registry/X/test of type M","time":"2016-02-26T15:11:35.956Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Attempting to read \"/var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/registry/reproduce/registry/X/test\"","time":"2016-02-26T15:11:35.957Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Adding key config/A/foo, value:\nbar","time":"2016-02-26T15:11:35.958Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Adding key config/B/bar, value:\nscooby","time":"2016-02-26T15:11:35.977Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Adding key registry/X/test, value:\nvalue","time":"2016-02-26T15:11:35.980Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Adding key registry/reproduce.ref, value:\ne4db78cdc0f4eccb54fae099cfaedfe0b54502d1","time":"2016-02-26T15:11:35.989Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Adding key config/reproduce.ref, value:\nefd6d007cb0d898915480a5f07393709da1a0fa9","time":"2016-02-26T15:11:35.991Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":40,"msg":"Purging branch cache /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/config/reproduce for branch reproduce in repo config","time":"2016-02-26T15:11:35.994Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":40,"msg":"Purging branch cache /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/registry/reproduce for branch reproduce in repo registry","time":"2016-02-26T15:11:35.995Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Adding key registry/reproduce.ref, value:\nnull","time":"2016-02-26T15:11:36.016Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Adding key config/reproduce.ref, value:\nnull","time":"2016-02-26T15:11:36.017Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Running git clone -b reproduce https://github.com/harnash/git2consul_test.git reproduce in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/config","time":"2016-02-26T15:11:36.021Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Running git clone -b reproduce https://github.com/harnash/git2consul_test.git reproduce in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/registry","time":"2016-02-26T15:11:36.024Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stderr:\nCloning into 'reproduce'...","time":"2016-02-26T15:11:36.931Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Running git log -n 1 --pretty=format:\"%H\" in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/registry/reproduce","time":"2016-02-26T15:11:36.932Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stdout:\n76a921700352e38e5174231de68b0d3af6359b69","time":"2016-02-26T15:11:36.939Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Running git ls-tree --name-status -r HEAD in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/registry/reproduce","time":"2016-02-26T15:11:36.941Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stderr:\nCloning into 'reproduce'...","time":"2016-02-26T15:11:36.946Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Running git log -n 1 --pretty=format:\"%H\" in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/config/reproduce","time":"2016-02-26T15:11:36.946Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stdout:\nconfig/A/foo\nregistry/X/test","time":"2016-02-26T15:11:36.950Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Handling record config/A/foo of type M","time":"2016-02-26T15:11:36.950Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Handling record registry/X/test of type M","time":"2016-02-26T15:11:36.950Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Attempting to read \"/var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/registry/reproduce/registry/X/test\"","time":"2016-02-26T15:11:36.950Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Adding key registry/X/test, value:\nvalue","time":"2016-02-26T15:11:36.951Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Adding key registry/reproduce.ref, value:\n76a921700352e38e5174231de68b0d3af6359b69","time":"2016-02-26T15:11:36.954Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stdout:\n76a921700352e38e5174231de68b0d3af6359b69","time":"2016-02-26T15:11:36.957Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Running git ls-tree --name-status -r HEAD in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/config/reproduce","time":"2016-02-26T15:11:36.960Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":30,"msg":"Initialized branch reproduce from registry","time":"2016-02-26T15:11:36.963Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":20,"msg":"Branches initialized","time":"2016-02-26T15:11:36.963Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":20,"msg":"Polling hook initialized with 1 minute intervals","time":"2016-02-26T15:11:36.964Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":30,"msg":"Loaded repo registry","time":"2016-02-26T15:11:36.964Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stdout:\nconfig/A/foo\nregistry/X/test","time":"2016-02-26T15:11:36.968Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Handling record config/A/foo of type M","time":"2016-02-26T15:11:36.968Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Attempting to read \"/var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/config/reproduce/config/A/foo\"","time":"2016-02-26T15:11:36.968Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Handling record registry/X/test of type M","time":"2016-02-26T15:11:36.968Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Adding key config/A/foo, value:\nbar","time":"2016-02-26T15:11:36.969Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Adding key config/reproduce.ref, value:\n76a921700352e38e5174231de68b0d3af6359b69","time":"2016-02-26T15:11:36.982Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":30,"msg":"Initialized branch reproduce from config","time":"2016-02-26T15:11:36.987Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":20,"msg":"Branches initialized","time":"2016-02-26T15:11:36.987Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":20,"msg":"Polling hook initialized with 1 minute intervals","time":"2016-02-26T15:11:36.988Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":30,"msg":"Loaded repo config","time":"2016-02-26T15:11:36.988Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Polling branch reproduce of repo config","time":"2016-02-26T15:11:40.989Z","v":0}

First commit

{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Polling branch reproduce of repo registry","time":"2016-02-26T15:11:55.967Z","v":0}

First push

{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Running git pull origin reproduce in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/config/reproduce","time":"2016-02-26T15:12:40.996Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stdout:\nUpdating 76a9217..55c55f8\nFast-forward\n config/B/bar | 1 +\n 1 file changed, 1 insertion(+)\n create mode 100644 config/B/bar","time":"2016-02-26T15:12:41.946Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stderr:\nFrom https://github.com/harnash/git2consul_test\n * branch            reproduce  -> FETCH_HEAD\n   76a9217..55c55f8  reproduce  -> origin/reproduce","time":"2016-02-26T15:12:41.947Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Running git log -n 1 --pretty=format:\"%H\" in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/config/reproduce","time":"2016-02-26T15:12:41.947Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stdout:\n55c55f8edb25a0caff3f07d1b63e9c2eb0d75847","time":"2016-02-26T15:12:41.953Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Running git diff --name-status 76a921700352e38e5174231de68b0d3af6359b69 55c55f8edb25a0caff3f07d1b63e9c2eb0d75847 in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/config/reproduce","time":"2016-02-26T15:12:41.955Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stdout:\nA\tconfig/B/bar","time":"2016-02-26T15:12:41.962Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"config/B/bar","time":"2016-02-26T15:12:41.963Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Handling record config/B/bar of type A","time":"2016-02-26T15:12:41.963Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Attempting to read \"/var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/config/reproduce/config/B/bar\"","time":"2016-02-26T15:12:41.963Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Adding key config/B/bar, value:\nscooby","time":"2016-02-26T15:12:41.963Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Adding key config/reproduce.ref, value:\n55c55f8edb25a0caff3f07d1b63e9c2eb0d75847","time":"2016-02-26T15:12:41.966Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":20,"msg":"Updates in branch reproduce complete","time":"2016-02-26T15:12:41.972Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Running git pull origin reproduce in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/registry/reproduce","time":"2016-02-26T15:12:55.976Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stdout:\nUpdating 76a9217..55c55f8\nFast-forward\n config/B/bar | 1 +\n 1 file changed, 1 insertion(+)\n create mode 100644 config/B/bar","time":"2016-02-26T15:12:56.877Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stderr:\nFrom https://github.com/harnash/git2consul_test\n * branch            reproduce  -> FETCH_HEAD\n   76a9217..55c55f8  reproduce  -> origin/reproduce","time":"2016-02-26T15:12:56.877Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Running git log -n 1 --pretty=format:\"%H\" in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/registry/reproduce","time":"2016-02-26T15:12:56.877Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stdout:\n55c55f8edb25a0caff3f07d1b63e9c2eb0d75847","time":"2016-02-26T15:12:56.884Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Running git diff --name-status 76a921700352e38e5174231de68b0d3af6359b69 55c55f8edb25a0caff3f07d1b63e9c2eb0d75847 in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/registry/reproduce","time":"2016-02-26T15:12:56.885Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stdout:\nA\tconfig/B/bar","time":"2016-02-26T15:12:56.892Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"config/B/bar","time":"2016-02-26T15:12:56.892Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Handling record config/B/bar of type A","time":"2016-02-26T15:12:56.892Z","v":0}


Second commit

Second push

{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Running git pull origin reproduce in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/config/reproduce","time":"2016-02-26T15:13:41.004Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stdout:\nUpdating 55c55f8..64848a2\nFast-forward\n registry/Y/key1 | 1 +\n 1 file changed, 1 insertion(+)\n create mode 100644 registry/Y/key1","time":"2016-02-26T15:13:42.806Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stderr:\nFrom https://github.com/harnash/git2consul_test\n * branch            reproduce  -> FETCH_HEAD\n   55c55f8..64848a2  reproduce  -> origin/reproduce","time":"2016-02-26T15:13:42.806Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Running git log -n 1 --pretty=format:\"%H\" in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/config/reproduce","time":"2016-02-26T15:13:42.806Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stdout:\n64848a277a049aece4942b6c10b05c682db8d54f","time":"2016-02-26T15:13:42.815Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Running git diff --name-status 55c55f8edb25a0caff3f07d1b63e9c2eb0d75847 64848a277a049aece4942b6c10b05c682db8d54f in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/config/reproduce","time":"2016-02-26T15:13:42.817Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"stdout:\nA\tregistry/Y/key1","time":"2016-02-26T15:13:42.825Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"registry/Y/key1","time":"2016-02-26T15:13:42.826Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":75995,"level":10,"msg":"Handling record registry/Y/key1 of type A","time":"2016-02-26T15:13:42.826Z","v":0}
```

it seems to get stalled after the last entry....

**Comment by ryanbreen** [comment]
You are a gentlemen and a scholar!  I'll take a look.

**Comment by harnash** [comment]
I hope it helps :)

**Comment by ryanbreen** [comment]
Cool, found it!  The issue was that if we were using `source_root` and the last item in a commit happened not to have been within the `source_root`'s scope, the callback for the update operation would never fire.  Can you grab master and verify that it now works for your test?

**Comment by ryanbreen** [comment]
The fix is deployed in 0.12.2.  I'm going to close this, but feel free to reopen if that's not a complete fix.

**Comment by harnash** [comment]
Thanks! I will test it ASAP.

**Comment by harnash** [comment]
Hey! I'm sorry to report that I can still reproduce the problem. It fails on third commit. It tries to update the Consul but stalls and even after restart process just exits without any significant reason.

```
{"name":"git2consul","hostname":"wolfpit","pid":56696,"level":10,"msg":"Running git pull origin reproduce in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/config/reproduce","time":"2016-03-03T22:29:15.020Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":56696,"level":10,"msg":"stdout:\nUpdating 4124679..38e1699\nFast-forward\n registry/Y/key1 | 1 +\n 1 file changed, 1 insertion(+)\n create mode 100644 registry/Y/key1","time":"2016-03-03T22:29:15.784Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":56696,"level":10,"msg":"stderr:\nFrom https://github.com/harnash/git2consul_test\n * branch            reproduce  -> FETCH_HEAD\n   4124679..38e1699  reproduce  -> origin/reproduce","time":"2016-03-03T22:29:15.784Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":56696,"level":10,"msg":"Running git log -n 1 --pretty=format:\"%H\" in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/config/reproduce","time":"2016-03-03T22:29:15.784Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":56696,"level":10,"msg":"stdout:\n38e169947a5f211a7bfaa66a60ebea53b93aa8fd","time":"2016-03-03T22:29:15.790Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":56696,"level":10,"msg":"Running git diff --name-status 4124679a707afeb3d32eca769e05f041556551dd 38e169947a5f211a7bfaa66a60ebea53b93aa8fd in /var/folders/zv/shx7pbtd5179zkrfw0dz12dr0000gp/T/config/reproduce","time":"2016-03-03T22:29:15.792Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":56696,"level":10,"msg":"stdout:\nA\tregistry/Y/key1","time":"2016-03-03T22:29:15.799Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":56696,"level":10,"msg":"registry/Y/key1","time":"2016-03-03T22:29:15.799Z","v":0}
{"name":"git2consul","hostname":"wolfpit","pid":56696,"level":10,"msg":"Handling record registry/Y/key1 of type A","time":"2016-03-03T22:29:15.799Z","v":0}
```

**Comment by ryanbreen** [comment]
Bummer! I'll take a look.

**Comment by ryanbreen** [comment]
OK, test master again.  There's a decent chance we got it this time.

**Comment by harnash** [comment]
Yup! That did it! Thank you very much.

**Comment by ryanbreen** [comment]
Cool. I'll push a build.

**Comment by ryanbreen** [comment]
Thanks for all the help on this!
